name: Deploy to GitHub Pages

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build
        run: |
          npm run build
          # SPA fallback so /checkin (and any deep link) works on GH Pages
          cp dist/index.html dist/404.html
          # Write CNAME so GH Pages knows your custom domain
          echo "brooklynpoker.club" > dist/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
